#pragma comment(lib, "ws2_32.lib")
#include <WinSock2.h>
#include <ws2tcpip.h>
#include <iostream>
#include <Employer.hpp>
#include <Worker.hpp>
#include "version.h"        //will be generated by CMake
#include "path.h"           //will be generated by CMake

#define _WINSOCK_DEPRECATED_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#pragma warning(disable: 4996)

#define PORT 80

using namespace std;

static void cmd_parse(const int argc, const char* argv[]);
static void print_help(string aName);
static void print_version();
static void print_path();

SOCKET Connections[100];
int Counter = 0;

enum Packet{
	P_Worker,
	P_Employer
};

void ClientHandler(int index)
{
	Packet packettype;
	recv(Connections[index], (char*)&packettype, sizeof(Packet), NULL);
	
	switch (packettype)
	{
	case P_Worker:
	{
		Packet_Worker packettype1;
		cout << "Worker " << endl;

		while(true)
		{
			recv(Connections[index], (char*)&packettype1, sizeof(Packet_Worker), NULL);

			if(!ProcessPacket(index, packettype1, Counter, Connections))
			{
				break;
			}
		}
		break;
	}
	case P_Employer:
	{
		Packet_Employer packettype1;
		cout << "Employer " << endl;

		while(true)
		{
			recv(Connections[index], (char*)&packettype1, sizeof(Packet_Employer), NULL);

			if(!ProcessPacket(index, packettype1, Counter, Connections))
			{
				break;
			}
		}
		break;
	}
	
	default:
		cout << "Unrecognized packet: " << packettype << endl;
		break;
	}
}

int main(int argc, char* argv[])
{
	if (argc > 1)
	{
		cmd_parse(argc, const_cast<const char**>(argv));
		return 0;
	}

	WSAData wsaData;
	WORD DLLVersion = MAKEWORD(2, 1);
	if (WSAStartup(DLLVersion, &wsaData) != 0)
	{
		cout << "Error" << endl;
		exit(1);
	}

	SOCKADDR_IN addr;
	int sizofaddr = sizeof(addr);
	addr.sin_addr.s_addr = INADDR_ANY;
	addr.sin_port = htons(PORT);
	addr.sin_family = AF_INET;

	SOCKET sListen = socket(AF_INET, SOCK_STREAM, NULL);
	bind(sListen, (SOCKADDR*)&addr, sizeof(addr));
	listen(sListen, SOMAXCONN);

	SOCKET newConnection;
	for(int i = 0; i < 100; i++)
	{
		newConnection = accept(sListen, (SOCKADDR*)&addr, &sizofaddr);

		if (newConnection == 0)
		{
			cout << "Error #2\n";
		}
		else
		{
			cout << "Client " << i + 1 << " Connected!\n";
		}

		Connections[i] = newConnection;
		Counter++;
		CreateThread(NULL, NULL, (LPTHREAD_START_ROUTINE)ClientHandler, (LPVOID)(i), NULL, NULL);
	}

	system("pause");
	return 0;
}

static void print_help(string aName) {
	cout
		<< "Usage: " << aName << "<option(s)>\n"
		<< "Options:\n"
		<< "\t-h, --help    Show this massage\n"
		<< "\t-v, --version Show version of program\n"
		<< "\t-p, --path    Show path\n"
		<< endl;
}

static void print_version()
{
	cout << "Version: " << g_version << endl;
}

static void print_path()
{
	cout << "Path to source of the program: " << g_sourse_path << endl;
	cout << "Path to binary of the program: " << g_binary_path << endl;
}

static void cmd_parse(const int argc, const char* argv[]) {
	for (int i = 1; i < argc; ++i)
	{
		string param_name = argv[i];
		if ((param_name == "-h") || (param_name == "--help"))
		{
			print_help(argv[0]);
			continue;
		}
		if ((param_name == "-v") || (param_name == "--version"))
		{
			print_version();
			continue;
		}
		if ((param_name == "-p") || (param_name == "--path"))
		{
			print_path();
			continue;
		}
	}
}