name: C++ CI

on:
  push:
    branches: [dev]
    paths:
      - 'backend/**'
  pull_request:
    branches: [dev, master]
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Get repository code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Cache Google Test
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/googletest
            ./backend/build/googletest
          key: ${{ runner.os }}-googletest-${{ hashFiles('backend/tests/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-googletest-

      - name: Install dependencies
        working-directory: ./backend
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libssl-dev

      - name: Configure CMake and build project
        working-directory: ./backend
        shell: bash
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --parallel 4

      - name: Run tests
        working-directory: ./backend/build
        run: |
          ctest --output-on-failure
