name: Demo Workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello world!
      - name: Print a few lines
        run: |
          echo 1
          echo 2
