name: Flutter CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Get repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2"
          channel: stable
          cache: true

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          flutter pub upgrade --major-versions
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
        env:
          FLUTTER_PUB_CACHE: /tmp/flutter_pub_cache

      - name: Run tests
        working-directory: ./frontend
        run: flutter test --test-randomize-ordering-seed=random

      - name: Build debug APK
        working-directory: ./frontend
        if: github.ref == 'refs/heads/dev'
        run: flutter build apk --debug
