name: Flutter CD

on:
  push:
    tags: [ 'v*.*.*' ]  # Запуск при создании тега (например, v1.0.0)

jobs:
  build-and-deploy:
    runs-on: macos-latest  # Требуется для сборки iOS

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Install dependencies
        run: |
          flutter pub get
          cd ios && pod install

      - name: Build Android (release)
        run: flutter build apk --release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}  # Секреты из настроек репозитория

      - name: Build iOS (release)
        run: flutter build ipa --export-options-plist=ios/ExportOptions.plist

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-builds
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/ios/ipa/*.ipa